# server port
server:
  port: 8080

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/sampledb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbbdfsfefasdfefsdfasdvasefresafesadfaesfsdsf
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: trip # server 1
      # group-id: foo # server 2
    template:
      default-topic: chatroom
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: H92k7eYJnZJrSdWrKtY1
            client-secret: c8AjL9peFV
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - gender
              - birthyear
              - birthday
              - mobile
          google:
            client-name: google
            client-id: 48844342602-9gndagamflovi2kb59dudd1cm3ri7d7o.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          kakao:
            client-id: f6c26ee446c5636a6e9cf455da991457
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.trip.app.model

# API
service:
  placeKey: "aEszZJrRS7J3uIHinlD6%2BXf40lXZ0bwXuXsakXfMelXFrpdnIqaKb2r1qffl8v954ZIh2UNtlbh%2FhL0%2B2%2FeV2g%3D%3D"
